#!/bin/sh
echo "build started..."
#sleep 4
echo "build completed..."
#sleep 1
echo "tests started..."
#sleep 4
echo "tests completed..."
#sleep 1
echo "starting server..."
#sleep 4
echo "server running"
exit 0