version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: openpgp
    versions:
    - "> 2.6.2"
  - dependency-name: npm
    versions:
    - 6.14.11
    - 6.14.12
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.17
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: karma
    versions:
    - 6.0.0
    - 6.0.3
    - 6.1.0
    - 6.1.1
  - dependency-name: jasmine-core
    versions:
    - 3.6.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: puppeteer
    versions:
    - "> 2.0.0"
