#!/bin/sh
echo "build started..."
sleep 0.1
echo "build completed..."
sleep 0.1
echo "tests started..."
sleep 0.1
echo "tests completed..."
sleep 0.1
echo "starting server..."
sleep 0.1
echo "server running"
exit 0