const fs = require('fs')
const path = require('path')

const { E } = require('../..')

const errorFile = path.join(__dirname, '..', '..', 'src', 'errors.d.ts')

const thisFile = path.relative(path.dirname(errorFile), __filename)

let contents = `// autogenerated by ${thisFile}
export const E: {\n`

for (const [key, value] of Object.entries(E)) {
  contents += `  ${key}: '${value}',\n`
}
contents += `};\n`

fs.writeFileSync(errorFile, contents)
