export { GitConfigManager } from './managers/GitConfigManager'
export { GitShallowManager } from './managers/GitShallowManager'
export { GitIndexManager } from './managers/GitIndexManager'
export { GitObjectManager } from './managers/GitObjectManager'
export { GitRefsManager } from './managers/GitRefsManager'
export { GitRemoteHTTP } from './managers/GitRemoteHTTP'
