export { GitConfigManager } from './managers/GitConfigManager'
export { GitShallowManager } from './managers/GitShallowManager'
export { GitIndexManager } from './managers/GitIndexManager'
export { GitIgnoreManager } from './managers/GitIgnoreManager'
export { GitObjectManager } from './managers/GitObjectManager'
export { GitRefManager } from './managers/GitRefManager'
export { GitRemoteHTTP } from './managers/GitRemoteHTTP'
